### ISSUE TITLE
Missing clipboard constants

### ISSUE THREAD

**Issue by withoutboats** [gtk-rs/gdk#120]
As far as I can tell, this crate is missing bindings to the `GDK_SELECTION_CLIPBOARD`, `GDK_SELECTION_PRIMARY`, and `GDK_SELECTION_SECONDARY` constants. These constants are necessary to implement cut/copy/paste with GTK.

**Comment by GuillaumeGomez** [comment]
Indeed, strange...

**Comment by gkoz** [comment]
Huh, that's an interesting case. Apparently these constants aren't available in gir definitions.

The way to bind the `GdkAtom` type has not been settled yet. I'm leaning toward not exposing it at all and converting to/from strings transparently. The significance of performance impact of this approach is not quite clear... These constants would then be strings.

**Comment by withoutboats** [comment]
Hey I don't want to be a bother, but is there any progress on this? Copy paste is a blocker for me to release an alpha of the [terminal emulator](https://github.com/withoutboats/notty) I'm working on.

If you're not ready to commit to any particular strategy for defining these constants, I'm happy to maintain something myself in my repo, but I don't understand GDK or C all that well, and my attempts to provide bindings for them have failed. :-\

**Comment by GuillaumeGomez** [comment]
No, sorry. I'll add them by hand as soon as possible.

**Comment by gkoz** [comment]
After thinking a bit more I suppose it's more straightforward to actually use the `Atom` type, implement `From<&str>` for it and define these constants manually. There's an issue that the generator tries to take it by reference but it should probably be passed by value (it's `Copy` after all).

**Comment by Susurrus** [comment]
I'm actually looking to use the `GDK_SELECTION_*` constants as well, but I didn't find them in the code, just this old issue. If this was indeed implemented, what's the proper way to get `GDK_SELECTION_CLIPBOARD`?

**Comment by GuillaumeGomez** [comment]
Hum, I don't find either. Also not in gdk_sys file: https://github.com/gtk-rs/sys/blob/master/gdk-sys/src/lib.rs

So it just disappeared?

**Comment by Susurrus** [comment]
Well the commit that closed this issue never implemented it. Just implemented `From<&str>` I guess.

**Comment by GuillaumeGomez** [comment]
Well, I guess it's re-generate the gdk-sys. Not sure I'll have the time today so don't hesitate to do it.

**Comment by EPashkin** [comment]
It not in gir, so regen not work.

Seems it need implemented in https://github.com/gtk-rs/gdk/blob/master/src/atom.rs#L11 or directily in lib

**Comment by Susurrus** [comment]
Yeah, there're [several constants missing](https://github.com/linuxmint/gtk/blob/master/gdk/gdkselection.h). I'll file a PR for this if it's as easy as adding them to `src/atom.rs`.
