### ISSUE TITLE
gdk::EventButton is missing a "get_button()" function

### ISSUE THREAD

**Issue by fuchsnj** [gtk-rs/gdk#121]
You can do `event.as_ref().button` but a convenience method would be nice

**Comment by EPashkin** [comment]
Feel free to add PR.
Minor variant just add function to https://github.com/gtk-rs/gdk/blob/master/src/event_button.rs#L13-L27.
Better: create rusted enum on https://github.com/gtk-rs/sys/blob/master/gdk-sys/src/lib.rs#L697-L699 using https://github.com/gtk-rs/gdk/blob/master/src/auto/enums.rs as example.

**Comment by gkoz** [comment]
I don't trust the docs saying the button range is 1-5, an enum likely isn't appropriate.

**Comment by EPashkin** [comment]
Seems this can be closed
