### ISSUE TITLE
Failure building gdk on Rust 1.13

### ISSUE THREAD

**Issue by Susurrus** [gtk-rs/gdk#134]
My projects have been targetting Rust 1.13 as a minimum build version and I recently ran into a problem building gdk (through the glib and gtk dependencies) for my GUI program:
```
     Running `rustc /root/.cargo/git/checkouts/gdk-0e2106e2e12a0cc1/8b3342528ee9c85bf5ecf97c788b2cc3d531e7d8/src/lib.rs --crate-name gdk --crate-type lib -g --cfg feature=\"v3_6\" --cfg feature=\"pango\" --cfg feature=\"v3_16\" --cfg feature=\"v3_12\" --cfg feature=\"v3_14\" --cfg feature=\"v3_8\" --cfg feature=\"gdk-pixbuf\" --cfg feature=\"v3_18\" --cfg feature=\"v3_10\" --cfg feature=\"gio\" --cfg feature=\"v3_20\" --cfg feature=\"cairo-rs\" --cfg feature=\"gdk-sys\" -C metadata=1f87422b5add9ed8 -C extra-filename=-1f87422b5add9ed8 --out-dir /builds/susurrus/gattii/target/debug/deps --emit=dep-info,link -L dependency=/builds/susurrus/gattii/target/debug/deps --extern bitflags=/builds/susurrus/gattii/target/debug/deps/libbitflags-1efefdc447eb53f2.rlib --extern glib_sys=/builds/susurrus/gattii/target/debug/deps/libglib_sys-8f1dec70df9c8640.rlib --extern cairo=/builds/susurrus/gattii/target/debug/deps/libcairo-77d84e4bc57ccadc.rlib --extern pango=/builds/susurrus/gattii/target/debug/deps/libpango-7d1db9e45a06c17d.rlib --extern gdk_sys=/builds/susurrus/gattii/target/debug/deps/libgdk_sys-cd0070267421ce7b.rlib --extern libc=/builds/susurrus/gattii/target/debug/deps/liblibc-e1db4c5f3a4f3c2f.rlib --extern gdk_pixbuf=/builds/susurrus/gattii/target/debug/deps/libgdk_pixbuf-06be090bf3460918.rlib --extern gio=/builds/susurrus/gattii/target/debug/deps/libgio-f3f1e1d7dd69eae8.rlib --extern glib=/builds/susurrus/gattii/target/debug/deps/libglib-05904638e40d7bdc.rlib --cap-lints allow -L native=/usr/lib/x86_64-linux-gnu -L native=/usr/lib/x86_64-linux-gnu -L native=/usr/lib/x86_64-linux-gnu -L native=/usr/lib/x86_64-linux-gnu -L native=/usr/lib/x86_64-linux-gnu -L native=/usr/lib/x86_64-linux-gnu -L native=/usr/lib/x86_64-linux-gnu`
error[E0252]: a type named `EventMask` has already been imported in this module
   --> /root/.cargo/git/checkouts/gdk-0e2106e2e12a0cc1/8b3342528ee9c85bf5ecf97c788b2cc3d531e7d8/src/lib.rs:136:9
    |
24  | pub use auto::*;
    |         -------- previous import of `EventMask` here
...
136 | pub use ffi::GdkEventMask as EventMask;
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ already imported

error[E0252]: a type named `WindowHints` has already been imported in this module
   --> /root/.cargo/git/checkouts/gdk-0e2106e2e12a0cc1/8b3342528ee9c85bf5ecf97c788b2cc3d531e7d8/src/lib.rs:151:9
    |
24  | pub use auto::*;
    |         -------- previous import of `WindowHints` here
...
151 | pub use ffi::GdkWindowHints as WindowHints;
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ already imported

error[E0252]: a type named `DragAction` has already been imported in this module
   --> /root/.cargo/git/checkouts/gdk-0e2106e2e12a0cc1/8b3342528ee9c85bf5ecf97c788b2cc3d531e7d8/src/lib.rs:134:9
    |
24  | pub use auto::*;
    |         -------- previous import of `DragAction` here
...
134 | pub use ffi::GdkDragAction as DragAction;
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ already imported

error: aborting due to 3 previous errors

error: Could not compile `gdk`.
```

These failures occur on `x86_64-unknown-linux-gnu`, `x86_64-pc-windows-gnu`, and `i686-pc-windows-gnu` only for 1.13. The same codebase for nightly and stable (currently 1.15.1) builds succeed.

I guess my first question is this an actual bug, either with our code of 1.13. And secondly, what is the oldest Rust supported by gtk-rs and friends as the README doesn't specify anything?

**Comment by GuillaumeGomez** [comment]
Strange... However we cannot handle to support old rust releases...

**Comment by EPashkin** [comment]
@Susurrus, its effect your #133 :wink:
Lines 134, 136, 151 need be removed as we define new biflags.
But after it removal 14 errors `expected struct 'auto::flags::EventMask', found struct 'ffi::GdkEventMask'` appears, that also need be fixed by adding `.to_glib()`.

Seems it really bug in new rust, it allow import different classes by same name.

**Comment by Susurrus** [comment]
@GuillaumeGomez So there's no minimum Rust version you guys want to specify? gtk-rs will only be supported on stable?

@EPashkin I've tested compilation on `1.14.0`, `1.13.0`, and `1.15.1` locally and only `1.15.1` succeeds. Looks like `1.15` introduced some name resolution changes in the drive towards Macros 2.0: https://github.com/rust-lang/rfcs/blob/master/text/1560-name-resolution.md#changes-to-name-resolution-rules. So it's possible to re-import names if they refer to the same item without an error.

I've also tried working on fixing this problem by deleting the `use ffi::...` lines you mentioned and I get conflicting type errors that I'm not certain how to resolve. After #133 there are now duplicate declarations of a couple of enums, specifically `DragAction`, `EventMask`, and `WindowHints`. It actually seems like the correct change here is to delete the generated one in this repo and keep the `pub use ffi::... as ...` statements. Is that a correct understanding?

**Comment by EPashkin** [comment]
IMHO correct is deleting `use ffi::` and fix all error with `.to_glib()` and `from_glib` as it allow of use these flags in generated code (`gir` assumed that flags converted with `.to_glib()`)
Final decision on @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Yes, we support stable and nightly. Like I said, we can't affort to support more than that. There is a new version every 6 weeks, which means 8 versions a year. That's just too much.

However, if there is a rust 2 version someday, we'll try to keep support for rust 1 (stable/nightly) as well.

**Comment by Susurrus** [comment]
@GuillaumeGomez That's reasonable and I think it'd be helpful to have that support declared explicitly in the README.

So if there isn't an intent to support anything below the latest stable version, is there even a need to "fix" this since it isn't an error on 1.15.1? If this should be fixed because it's an error, is there anyway to change the testing such that this will become an error for future changes to the library to this can be caught if it happens again in the future?

**Comment by GuillaumeGomez** [comment]
A thing that could be improved though would be to not import more than needed. But that'd require quite a lot of changes in `gir`...

**Comment by Susurrus** [comment]
So from what @EPashkin said, it sounded like there was a change that should be done. But @GuillaumeGomez is there anything to do here or should I just close this issue?

**Comment by GuillaumeGomez** [comment]
We definitely need to improve imports. I prefer to avoid any potential side effects as much as possible. So let's keep it open if you don't mind.

**Comment by Susurrus** [comment]
Sure, that's fine with me. I was trying to understand what @EPashkin, but it sounds like the right answer is to not bulk-import things. Is that correct?

**Comment by GuillaumeGomez** [comment]
Indeed, we'd need to make more clever and specific imports. I'll try to make a PR for it when I have time.

**Comment by Susurrus** [comment]
But is there any need for that if it isn't a compilation error? If you don't want to support older Rust versions, maybe it's not worth the effort?

**Comment by GuillaumeGomez** [comment]
The code isn't *clean* and that is bothering. That's a sufficient enough reason I guess? 😉

**Comment by Susurrus** [comment]
I can't argue with that; I also like clean code!

**Comment by EPashkin** [comment]
Gdk seems builds now with rustc 1.13.0 (2c6933acc 2016-11-07)
@Susurrus, can you test on your side and close issue it all Ok?

**Comment by Susurrus** [comment]
I don't know what overrides you were talking about, but I don't have any local overrides specified.

**Comment by Susurrus** [comment]
Latest commits fixed it, thanks guys! Now I did want to follow up on this and ask is supporting Rust 1.13 an explicit goal? I'd really like to make my project work that far back, but not unless gtk-rs explicitly supports it. If so, adding 1.13 to CI builds will help ensure that the minimum version will continue to be supported.

**Comment by GuillaumeGomez** [comment]
No, I think I wrote it somewhere but it don't want to *explicitly* support older versions than the current stable. However, PRs to support older versions are very welcome.

**Comment by Susurrus** [comment]
Sounds reasonable, thanks for clearing that up.
