### ISSUE TITLE
Rectangle from_glib_xx problem

### ISSUE THREAD

**Issue by EPashkin** [gtk-rs/gdk#136]
`Rectangle` has implementation of trait [`FromGlibPtr`](https://github.com/gtk-rs/gdk/blob/master/src/rectangle.rs#L75-L95) that contains `panic!()` in "full" branch.

Implementation mostly unused as `Rectangle` returned by out.
Only use is converting ffi-struct field in [`EventExpose`](https://github.com/gtk-rs/gdk/blob/master/src/event_expose.rs#L16).

Converting ffi-struct field IMHO legal usage and we can't disallow it, but `panic!()` better removed.
I see 2 way to fix:
- implement `From<*const ffi::GdkRectangle>` for `Rectangle`
- extract `FromGlibNonePtr` trait

First currently only needed changes in gdk and maybe in user crates.
Second need change almost all crates.
Both seems don't affect `Gir`.

@GuillaumeGomez, what you think?

PS. This issue also applied for other records that converting by direct copy ("direct" records: `PangoRectange`, maybe `GdkRGBA`, ...)

**Comment by GuillaumeGomez** [comment]
I think the first proposition is better.

**Comment by EPashkin** [comment]
Was wrong, `Gir` also affected due gtk needed these changes:
```diff
--- a/src/auto/cell_area.rs
+++ b/src/auto/cell_area.rs
@@ -430,7 +430,7 @@ where T: IsA<CellArea> {
     callback_guard!();
     let f: &Box_<Fn(&T, &CellRenderer, &CellEditable, &gdk::Rectangle, TreePath) + 'static> = transmute(f);
     let path = from_glib_full(ffi::gtk_tree_path_new_from_string(path));
-    f(&CellArea::from_glib_none(this).downcast_unchecked(), &from_glib_none(renderer), &from_glib_none(editable), &from_glib_none(cell_area), path)
+    f(&CellArea::from_glib_none(this).downcast_unchecked(), &from_glib_none(renderer), &from_glib_none(editable), &gdk::Rectangle::from(cell_area as * const _), path)
 }
 
 unsafe extern "C" fn apply_attributes_trampoline<T>(this: *mut ffi::GtkCellArea, model: *mut ffi::GtkTreeModel, iter: *mut ffi::GtkTreeIter, is_expander: glib_ffi::gboolean, is_expanded: glib_ffi::gboolean, f: glib_ffi::gpointer)

--- a/src/auto/widget.rs
+++ b/src/auto/widget.rs
@@ -3191,7 +3191,7 @@ unsafe extern "C" fn size_allocate_trampoline<T>(this: *mut ffi::GtkWidget, allo
 where T: IsA<Widget> {
     callback_guard!();
     let f: &Box_<Fn(&T, &Allocation) + 'static> = transmute(f);
-    f(&Widget::from_glib_none(this).downcast_unchecked(), &from_glib_none(allocation))
+    f(&Widget::from_glib_none(this).downcast_unchecked(), &Allocation::from(allocation as * const _))
 }
 
 unsafe extern "C" fn state_flags_changed_trampoline<T>(this: *mut ffi::GtkWidget, flags: ffi::GtkStateFlags, f: glib_ffi::gpointer)
```
I try change gir and add gdk PR after that

**Comment by GuillaumeGomez** [comment]
Ok!

**Comment by EPashkin** [comment]
Seems first way not does not work:
- `GdkEventButton` also don't have any functions and counts as "direct" record and have `from` in https://github.com/gtk-rs/gdk/blob/master/src/event.rs#L49-L52
- `cairo::Surface` also don't have any functions due "empty" .gir 😢 
I start to think that better ignore this issue

**Comment by EPashkin** [comment]
@GuillaumeGomez Extracting `FromGlibPtrNone` at minimum builds :wink: but need more time if you allow it.
I plan split `FromGlibPtr` to 3 parts: `FromGlibPtrNone`, `FromGlibPtrFull`, `FromGlibPtrBorrow` (currently only extracted None)
Also seems same better to with `FromGlibPtrContainer` as some of [implementation](https://github.com/gtk-rs/glib/blob/master/src/translate.rs#L1071-L1096) contains `unimplemented()!`

**Comment by GuillaumeGomez** [comment]
Sure, take your time.

**Comment by EPashkin** [comment]
`FromGlibPtrContainer` don't splited as it has many different cross calls.

**Comment by GuillaumeGomez** [comment]
Should be good now. Let's see if CIs confirm it.

**Comment by EPashkin** [comment]
Maybe better stop all appveyour that before https://ci.appveyor.com/project/GuillaumeGomez/gdk/build/1.0.155
