### ISSUE TITLE
GdkScreen signals

### ISSUE THREAD

**Issue by lukasstevens** [gtk-rs/gdk#146]
Hello, I would like to be able to use the signals of GdkScreen as described in the [documentation](https://developer.gnome.org/gdk3/stable/GdkScreen.html#GdkScreen-monitors-changed). I would implement them, but I am not sure how to do that. Maybe you can help me?

**Comment by EPashkin** [comment]
It was implemented recently see https://github.com/gtk-rs/gdk/blob/master/src/auto/screen.rs#L268

**Comment by GuillaumeGomez** [comment]
So target master instead of using the crates.io version.

**Comment by lukasstevens** [comment]
That's cool! I am on master. I'll try it.

**Comment by lukasstevens** [comment]
I have another question. How do I get all Screens to which my application has access to?

**Comment by EPashkin** [comment]
Maybe https://github.com/gtk-rs/gdk/blob/master/src/auto/display_manager.rs#L29 
as Display can have only one Screen https://developer.gnome.org/gdk3/stable/GdkDisplay.html#gdk-display-get-n-screens

**Comment by lukasstevens** [comment]
Thank you I just was looking into `Display`, but I was confused that there is a method to which you pass the screen number. If there really is only one screen then the method [get_screen](http://gtk-rs.org/docs/gdk/struct.Display.html?search=#method.get_screen) does not make much sense, does it? Especially since `get_n_screens` does not seem to be implemented.

**Comment by EPashkin** [comment]
It [implemented](https://github.com/gtk-rs/gdk/blob/master/src/auto/display.rs#L138)
Yes strange that `gdk_display_get_n_screens` deprecated in 3.10 but `gdk_display_get_screen` only in 3.20

**Comment by lukasstevens** [comment]
Thank you for answering my questions. I think this can be closed.
