### ISSUE TITLE
Missing keymaps

### ISSUE THREAD

**Issue by hungtcs** [gtk-rs/gdk#201]
Hello!  I can not find the api about key map, is it missing?

**Comment by GuillaumeGomez** [comment]
Are you talking about [this](http://gtk-rs.org/docs/gdk/enums/key/index.html)?

**Comment by hungtcs** [comment]
Yes! Ashamed,thank you.

**Comment by GuillaumeGomez** [comment]
Don't hesitate if you have other issues. ;)
