### ISSUE TITLE
add a method get_root_position() to EventMotion

### ISSUE THREAD

**Issue by pwil3058** [gtk-rs/gdk#205]
Sometimes one needs the position relative to the root of the screen rather than the widget.

pub fn get_root_position(&self) -> (f64, f64) {
        let x = self.as_ref().x_root;
        let y = self.as_ref().y_root;
        (x, y)
}

**Comment by EPashkin** [comment]
Agree, with `is_hint->bool`, `axes->Option((f65, f64))`, and `device->Device`
Feel free to fill PR

**Comment by GuillaumeGomez** [comment]
Solved so I close it.
