### ISSUE TITLE
Bindings for gdk_event_request_motions() missing

### ISSUE THREAD

**Issue by FreeFull** [gtk-rs/gdk#222]
GDK documentation: https://developer.gnome.org/gdk3/stable/gdk3-Events.html#gdk-event-request-motions

GTK 3.8 and onwards will always compress motion events, unless gdk_window_set_event_compression() is used to disable compression. gdk_event_request_motions() is the recommended way of decompressing the events in a handler, but it seems that the binding for it is missing. An alternative is the gdk_window_get_device_position() function, which does have a binding, but EventMotion doesn't seem to provide a .get_device() method on the Rust side.

**Comment by EPashkin** [comment]
@FreeFull `get_device` can be called on any event object as it implemented in "parent" `Event`, but seems it only in git version
