### ISSUE TITLE
Events are missing properties

### ISSUE THREAD

**Issue by CBurgener** [gtk-rs/gdk#230]
Many event objects are missing properties in rust compared to the gdk implementation.
Example: [gdk motion event](https://developer.gnome.org/gdk3/stable/gdk3-Event-Structures.html#GdkEventMotion) has a device property and [gtk-rs motion event](http://gtk-rs.org/docs/gdk/struct.EventMotion.html) does not.
Were these properties left out for a specific reason?

**Comment by EPashkin** [comment]
This class was written manually, so it was just skipped (maybe because no GdkDevice was generated at that time).

**Comment by cyrill-burgener** [comment]
Would it be useful to manually complete the implementations or are you planning on autogenerating these classes as well?

**Comment by GuillaumeGomez** [comment]
I'll add the missing functions this evening.

**Comment by CBurgener** [comment]
Great, thank you.

**Comment by GuillaumeGomez** [comment]
Don't close it until it's fixed! XD

**Comment by CBurgener** [comment]
Oops, pressed the wrong button
