### ISSUE TITLE
Proposal: use an `Option` for return value of `get_[predicted_]presentation_time()`

### ISSUE THREAD

**Issue by fengalin** [gtk-rs/gdk#250]
`get_presentation_time` & `get_predicted_presentation_time` [can both return `0` when the value is not available](https://developer.gnome.org/gdk3/stable/gdk3-GdkFrameTimings.html#gdk-frame-timings-get-predicted-presentation-time).

In Rust, returning `None` in this case would make it clear that the value shouldn't be used as is. I tried changing the signature to return an `Option` using Gir's `nullable = true`, but it didn't work.

What do you think about this change? If you agree, I'll open a PR.
Is there a Gir-way to handle this or should I use a manual implementation?

**Comment by EPashkin** [comment]
IMHO sound reasonable.
Can be done only with manual implementation.

**Comment by fengalin** [comment]
@EPashkin ok thanks. I'll do this soon then.

**Comment by fengalin** [comment]
Fixed per #251
