### ISSUE TITLE
setting _NET_WM_WINDOW_TYPE(ATOM)

### ISSUE THREAD

**Issue by MeisterTea** [gtk-rs/gdk#256]
Hi, how can I set this parameter for the ApplicationWindow instance ?
Also, same question for NET_WM_STRUT_PARTIAL and _NET_WM_STRUT(CARDINAL).

Thank you

**Comment by GuillaumeGomez** [comment]
Apparently, you can do it by calling [gdk::property_change](http://gtk-rs.org/docs/gdk/fn.property_change.html) function on your window (a little call to [upcast](http://gtk-rs.org/docs/gtk/trait.Cast.html#method.upcast) and you have your window).

I found [this topic](https://stackoverflow.com/questions/13455527/cant-change-net-wm-strut-partial-property) which talks about it. Maybe take a look at it?

**Comment by MeisterTea** [comment]
> Apparently, you can do it by calling [gdk::property_change](http://gtk-rs.org/docs/gdk/fn.property_change.html) function on your window (a little call to [upcast](http://gtk-rs.org/docs/gtk/trait.Cast.html#method.upcast) and you have your window).
> 
> I found [this topic](https://stackoverflow.com/questions/13455527/cant-change-net-wm-strut-partial-property) which talks about it. Maybe take a look at it?

It worked fine, thank you.
