### ISSUE TITLE
Pixbuf::new

### ISSUE THREAD

**Issue by lucaswerkmeister** [gtk-rs/gdk#28]
See discussion on ba7ccfc ([comment](https://github.com/rust-gnome/gdk/commit/ba7ccfce909fdffab5a123269e135b316910f958#commitcomment-11123651)). Summary:

- [ ] Add `Pixbuf::new_uninitialized`, directly calls `gdk_pixbuf_new`
- [ ] Make `Pixbuf::new` clear its newly allocated buffer
- [ ] Remove `unsafe` from `Pixbuf::new`

**Comment by GuillaumeGomez** [comment]
Thanks for opening this issue. I don't have time before tomorrow (or after tomorrow if very unlucky), so if anyone wanna do it, please do ! :-)

**Comment by gkoz** [comment]
If `set_alpha` is set, wouldn't initializing to all zeroes mean the image is transparent? This may not be a nice default. Maybe initialize to all `255`? I've no expertise in this area.

**Comment by lucaswerkmeister** [comment]
That might be a problem if people set the color on the `pixels` array manually and forget to set the alpha channel as well. Perhaps we could do `pixbuf::fill(0x000000ff)`. (Not sure if that’s significantly more expensive than just zeroing the memory.)

**Comment by gkoz** [comment]
We might also take the desired value as an argument and then pass it to `fill`. In that case we need to take care of the `fill` API first.

**Comment by GuillaumeGomez** [comment]
The alpha should __always__ be to 255 by default.

**Comment by gkoz** [comment]
Yeah but what if we just don't do default and require a specific value.

**Comment by GuillaumeGomez** [comment]
That's a common sense. alpha is always set to 1 (or 255) in order to print something. The alpha value is only set when you need your color to not be fully opaque.

**Comment by gkoz** [comment]
I'm saying, if we add a `struct IntRGBA(u8, u8, u8, u8)` (name not important right now) and make `fill` take it as an argument, we then add this argument to `new` and it will call out to `fill`.

**Comment by lucaswerkmeister** [comment]
I’d prefer that as well. We’ll have to call `fill` anyways (unless we initialize with opaqe white using `memset`), so we might as well make the color configurable. Both black and white would probably be useful to some users.

**Comment by GuillaumeGomez** [comment]
We can also ask for `Option<u8>` as last parameter. I really don't like to force a user to set alpha.

**Comment by gkoz** [comment]
There will be some kind of `fill` anyway. So if we want some consistency we'd probably be choosing between
```
fill(..., pixel: IntRGBA);
new(..., has_alpha: bool, pixel: IntRGBA); // ignores alpha if `has_alpha == false`
```
 and
```
fill(..., pixel: IntRGB); // what if the pixbuf has alpha?
fill_with_alpha(..., pixel: IntRGBA);
new(..., pixel: IntRGB);
new_with_alpha(..., pixel: IntRGBA);
```

**Comment by GuillaumeGomez** [comment]
I prefer your seonc proposition. If the pixbuf has pixbuf but the user doesn't provide it, we set it to 255 like in every other library in the world (yes, in the world, nothing less haha).

**Comment by lucaswerkmeister** [comment]
I prefer the first. I don’t think you’re suggesting different *types* for pixbufs with and without an alpha channel, and without that, the second variant doesn’t get you any additional type safety, so I just think it’s an unnecessary inconvenience and bloat.

**Comment by GuillaumeGomez** [comment]
What I want is just the possibilty to not give the alpha and have a default one.

**Comment by gkoz** [comment]
Should anyone really be using these primitives much? Is drawing on pixbufs manually a thing?

**Comment by lucaswerkmeister** [comment]
I suppose it’s “a thing” in that I do it, and I think it’s the right way to do what I want to do (render an image – without OpenGL – and display it). It’s probably not a *common* thing, so any bad decisions made here aren’t *that* bad in the grand scheme of things :)

**Comment by gkoz** [comment]
@lucaswerkmeister do you render it in your own buffer and copy into the pixbuf or use `get_pixels`?

**Comment by lucaswerkmeister** [comment]
I `get_pixels`, split it into multiple slices (`unsafe`ly), paint onto each slice in its own thread, and repeatedly `image.set_from_pixbuf(&pixbuf);` in the main loop to refresh it. ([Link](https://github.com/lucaswerkmeister/rfractalizer) if you’re curious.)

**Comment by gkoz** [comment]
Well as long as you use `get_pixels` a safe `new` doesn't buy you much does it?
Shouldn't we instead allow creating a `Pixbuf` from a `Vec` with the help of [gdk_pixbuf_new_from_data](https://developer.gnome.org/gdk-pixbuf/stable/gdk-pixbuf-Image-Data-in-Memory.html#gdk-pixbuf-new-from-data)

**Comment by gkoz** [comment]
And looking closer at the APIs I feel that the `color_space` argument can be removed. I don't believe in `GdkColorspace` getting a second variant any time soon.

**Comment by gkoz** [comment]
@lucaswerkmeister would you try out #33? I didn't test it...

**Comment by lucaswerkmeister** [comment]
I might be able to try it in a few hours, though I don’t immediately see what I’d gain from using it.

**Comment by gkoz** [comment]
This will allow you to render into your own `Vec<u8>` and then wrap it into a `Pixbuf` in safe code. (I assume you can safely do the multithreaded rendering into a `Vec`).

**Comment by gkoz** [comment]
Oh wait... I see the problem now :)

**Comment by lucaswerkmeister** [comment]
So I would create the `Pixbuf` and stick it into the image repeatedly, in the main loop?

**Comment by gkoz** [comment]
Yeah this is too limiting for your case...

**Comment by gkoz** [comment]
@lucaswerkmeister
You may want to look into using `GtkDrawingArea` for your purposes. It seems a better fit than `Image`.

**Comment by lucaswerkmeister** [comment]
I’m not sure about that… if I read the documentation correctly, it doesn’t keep drawing results, but instead asks me to redraw when it’s necessary (area is uncovered, window is un-minimized, etc.). That’s good for custom widgets in general, but it seems to me I’d still need to maintain some form of pixel buffer and drawing it to the widget periodically – not very different from what I do now. (One advantage would be that I wouldn’t need an `EventBox` wrapper.)

**Comment by gkoz** [comment]
Yes, you'll have to maintain the buffer yourself but interactions between threads will be under your complete control so you won't have to resort to unsafe shared access across library boundaries. Handling that is exactly what Rust is supposed to be good at. Also redrawing only the necessary parts should be more efficient than what you had to do with `Image` because of apparent `queue_draw` deficiency.

**Comment by gkoz** [comment]
Looks like the motivation for this feature is not strong enough at this time.
