### ISSUE TITLE
Compilation failing

### ISSUE THREAD

**Issue by GuillaumeGomez** [gtk-rs/gdk#301]
When I run `cargo build` (no options or anything) I get:

```
error[E0046]: not all trait items implemented, missing: `set_geometry_hints`
   --> src/window.rs:174:1
    |
151 |     fn set_geometry_hints(&self, geometry: &gdk_sys::GdkGeometry, geom_mask: WindowHints);
    |     -------------------------------------------------------------------------------------- `set_geometry_hints` from trait
...
174 | impl<O: IsA<Window>> WindowExtManual for O {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `set_geometry_hints` in implementation

error: aborting due to previous error
```

cc @sdroege @EPashkin

**Comment by sdroege** [comment]
It was removed in 8786402601d738b82f32674acf2bc15966a626fd. Not sure why? Seems very unrelated.

Also the function is in `WindowExt` and `WindowExtManual`. Autogenerated and manual. Needs some investigation what's up with that.

**Comment by EPashkin** [comment]
@sdroege Manual version was not removed when Geometry added,
https://github.com/gtk-rs/gdk/pull/302 is fix.
