### ISSUE TITLE
Clean up ciaro interactions

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gdk#308]
Currently, some methods are implemented as part of the ContextExt which shouldn't be the case.

The PixbufExt isn't loaded on prelude either.

**Comment by sdroege** [comment]
* `cairo_draw_from_gl()` should take the context as `&self`
* `cairo_surface_create_from_pixbuf()` should be removed from `ContextExt` (it's in `PixbufExt` where it should be)
* The traits should get `Gdk` as prefix of their name to prevent conflicts

**Comment by bilelmoussaoui** [comment]
Thanks! Will get a MR for this later today

**Comment by sdroege** [comment]
> Thanks! Will get a MR for this later today

Long day :) I've created https://github.com/gtk-rs/gdk/pull/312 for this now, please review if you have some time

**Comment by bilelmoussaoui** [comment]
Thanks for taking the time to fix it. Completely forgot about it
