### ISSUE TITLE
API stabilization

### ISSUE THREAD

**Issue by gkoz** [gtk-rs/gdk#32]
We should look at adding some structure to the crate's types organization. I don't like putting everything into the top-level namespace.
For example, the pixbufs stuff should stay in the `pixbuf` module. There we might also want to drop the `Pixbuf` prefix from most types (e.g. `PixbufLoader` -> `pixbuf::Loader`). I'm torn on the latter proposition though because renaming the classes may confuse people who read the official gnome docs. And this policy should be applied uniformly across the project.

**Comment by GuillaumeGomez** [comment]
Hum... I saw that with pixbuf, but I think this is more like a personal preference. However, in gtk it could be nice since we have a looooooooooooooot of files. And since we'll do it for gtk, why not for everything else ? >:-D

**Comment by gkoz** [comment]
Since we started generating the bindings the premise is not valid.
