### ISSUE TITLE
GdkPixbufExt: create_surface doesn't work with a None

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gdk#332]
I have added in https://github.com/gtk-rs/gdk/commit/2e14ec939cf9a484454fdbe70126b92c57ddfb64 the possibility to use the `create_surface` without passing a `GdkWindow`.

From what I understand, somehow `glib::IsA` doesn't seem to work correctly with an `Option<gdk::Window>` as I keep getting

```
402 |         let new_surface = pixbuf.create_surface(self.get_zoom() as i32, None).unwrap();
    |                                                                         ^^^^
    |                                                                         |
    |                                                                         expected reference, found enum `std::option::Option`
    |                                                                         help: consider borrowing here: `&None`
```

using `gdk::NONE_WINDOW` doesn't seem to help neither. Removing the use of `glib::IsA` in the patch linked above makes my code pass the build and works. 

After reading a bit about the use of `glib::IsA ` https://github.com/gtk-rs/glib/blob/e003445cfa3d32f057b355524e4c832b5273129f/src/object.rs#L76 
It seems that I shouldn't have used that in that patch as `gdk::Window` doesn't implement the `ToGlibPtr`

Am I missing something or should I send a patch to remove the use of `IsA` already?

**Comment by sdroege** [comment]
This should work

```
let new_surface = pixbuf.create_surface(self.get_zoom() as i32, None::<&gdk::Window>).unwrap();
```

> It seems that I shouldn't have used that in that patch as `gdk::Window` doesn't implement the `ToGlibPtr`

It's a `GObject` so it does implement that trait and lots of others. Why do you think it does not implement `ToGlibPtr`?

**Comment by EPashkin** [comment]
` let new_surface = pixbuf.create_surface(5 as i32, gdk::NONE_WINDOW).unwrap();`
compiles for me

**Comment by bilelmoussaoui** [comment]
Well, I can't get it to compile here with this 
```rust
use gdk::prelude::*;
fn main() {
    let pixbuf = gdk_pixbuf::Pixbuf::new(gdk_pixbuf::Colorspace::Rgb, false,  8, 100, 100).unwrap();
    let surface = pixbuf.create_surface(5 as i32, gdk::NONE_WINDOW).unwrap();
}
```

and these dependencies defined in Cargo.toml
```toml
gtk = { version = "0.8", features = ["v3_22"] }
glib = "0.9"
gio = { version = "0.8", features = ["v2_46"] }
gdk = "0.12"
gdk-sys = "0.9"
cairo-rs = { version = "0.8", features = ["png"] }
pango = "0.8"
gdk-pixbuf = "0.8"
```

**Comment by sdroege** [comment]
You need to use gdk from git. It's not in a release yet, and will only be in the 0.13 release (not 0.12.1).

**Comment by bilelmoussaoui** [comment]
I somehow completely missed checking whether it was released or not.
Sorry for the noise :)
