### ISSUE TITLE
Add GDK_EVENT_* & GDK_BUTTON_* to the public api

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gdk#336]
Per the discussion in that chat room

the gdk_button & gdk_event are exposed through the -sys crate only and should be part of the public API

Quoting ebassi

> There are a couple of defines that should be in the public API; like GDK_BUTTON_* and GDK_EVENT_PROPAGATE|STOP

**Comment by GuillaumeGomez** [comment]
The events more generally would need a closer look because I'm sure a few other things don't have bindings.

**Comment by sdroege** [comment]
`GDK_BUTTON_*` are added in https://github.com/gtk-rs/gdk/pull/352

@bilelmoussaoui want to go ahead and add the others you noticed are missing?
