### ISSUE TITLE
Use of gdk_sys::gdk_screen_get_default()

### ISSUE THREAD

**Issue by sergioArgerey** [gtk-rs/gdk#337]
Hi all,

I'm trying to port some of the logic of devilspie2 into a project written in rust.

https://git.savannah.gnu.org/cgit/devilspie2.git/tree/src/devilspie2.c#n136 

```
    unsafe {
        let _default_display = gdk_sys::gdk_display_get_default();

        let _default_screen = gdk_sys::gdk_display_get_screen(_default_display, 0);
        OR
        let _default_screen = gdk_sys::gdk_screen_get_default();

        let _windows = gdk_sys::gdk_screen_get_window_stack(_default_screen);

        // glib_sys::g_list_foreach (_windows, Some(call_from_c(), ptr::null_mut());             
        
    }
```

```
...
(process:15885): Gdk-CRITICAL **: 17:59:10.729: gdk_display_get_screen: assertion 'GDK_IS_DISPLAY (display)' failed

(process:15885): Gdk-CRITICAL **: 17:59:10.730: gdk_screen_get_window_stack: assertion 'GDK_IS_SCREEN (screen)' failed
...
```

I tried something like "export DISPLAY=:0" but I'm out of ideas.

**Comment by GuillaumeGomez** [comment]
Why aren't you using the non-sys gdk crate? It'll tell you exactly what's wrong.

**Comment by sdroege** [comment]
The warnings also tell you what exactly is going wrong here. `gdk_display_get_default()` return `NULL` and you're not checking for that before passing it onwards.

There's nothing special about the bindings here, if you use the -sys bindings directly you are effectively writing C. Please ask on the GTK mailing list for help about problems directly related to GTK/GDK and not the bindings.

@GuillaumeGomez Please close as this is a support request and not a bug.
