### ISSUE TITLE
unresolved import `gdk::Monitor` 

### ISSUE THREAD

**Issue by Srikanth-M-02** [gtk-rs/gdk#356]
Version:0.13.1

When I run cargo doc --open, also under Gdk there is no struct called Monitor

**Comment by GuillaumeGomez** [comment]
Very likely an artifact. I'm updating the doc generator in order to prevent these cases...

**Comment by GuillaumeGomez** [comment]
It's marked in the documentation: https://gtk-rs.org/docs/gdk/struct.Monitor.html

You need to enable the `v3_22` feature to have this type.
